name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x' # adjust this to your specific .NET version

    - name: Build and Publish
      run: |
        dotnet restore
        dotnet publish -c Release --no-restore

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: NBWSTech/bin/Release/net5.0/publish/wwwroot
        clean: true
